"""intake responses on delete restrict

Changes `intake_responses.booking_id` from ON DELETE CASCADE to RESTRICT, so
every foreign key into `bookings` now behaves the same way and nothing about a
booking can disappear quietly. See the deletion policy on the Booking model.

Why the original CASCADE was wrong: with every *other* key on RESTRICT, a
booking holding a payment, a notification or a reschedule link cannot be
deleted at all. So the cascade could only ever fire for a booking with none of
those — an expired pending one — which is precisely the case where the intake
answers are the only surviving record of what the person asked for. Mixed rules
also let a DELETE half-succeed.

REVIEW CHECKLIST — worked through, nothing outstanding:

  [x] Column type change? No. Constraint-only change; the column is untouched.
  [x] CHECK constraint depending on a dropped column? No column is dropped.
      The FK is dropped and recreated by name, which is exactly what the
      naming convention exists to make safe.
  [x] Exclusion constraint? Unaffected; it lives on `bookings`.
  [x] NOT NULL on a populated table? No new columns.
  [x] Does downgrade reverse upgrade? Yes — verified up -> down -> up with
      real booking and intake rows present, asserting that RESTRICT refuses
      the delete afterwards and CASCADE performs it again on the way down.
  [x] Anything lossy? No. No data is read, written or moved; only the
      referential action changes.

Note this is one autogenerate got *right*: it detected the changed `ondelete`
and emitted the drop-and-recreate unprompted. Recorded because the previous
three migrations all needed hand-fixing, and it would be wrong to leave the
impression that every migration does.

Revision ID: e68575c98769
Revises: bc737c0339e0
Create Date: 2026-08-13 06:04:11.303873

"""

from collections.abc import Sequence

from alembic import op

revision: str = "e68575c98769"
down_revision: str | Sequence[str] | None = "bc737c0339e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_intake_responses_booking_id_bookings"), "intake_responses", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_intake_responses_booking_id_bookings"),
        "intake_responses",
        "bookings",
        ["booking_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_intake_responses_booking_id_bookings"), "intake_responses", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_intake_responses_booking_id_bookings"),
        "intake_responses",
        "bookings",
        ["booking_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
