"""core models: services, availability, date overrides, settings

Autogenerated, then hand-edited in three places. Each edit is marked
HAND-WRITTEN below:

  1. `intake_questions` renders as `app.db.types.IntakeQuestions(...)` with an
     undefined `Text()`. Replaced with plain `postgresql.JSONB`. Migrations
     must not import application types: this file has to keep running years
     from now against whatever the code has become, and the custom type only
     matters at the ORM layer anyway — the underlying column really is JSONB.
  2. `downgrade()` drops the tables but leaves the `date_override_type` enum
     type behind, so a downgrade-then-upgrade fails with "type already
     exists". Autogenerate never emits the DROP TYPE.
  3. `sa.Enum(..., create_type=False)` plus an explicit create, so the type is
     created exactly once and in a known order.

Revision ID: 7c6380fb1b7c
Revises: 15cc4a0cad0a
Create Date: 2026-08-10 00:39:49.861752

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7c6380fb1b7c"
down_revision: str | Sequence[str] | None = "15cc4a0cad0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# HAND-WRITTEN: declared once so upgrade and downgrade agree on the name.
# create_type=False stops create_table from implicitly emitting CREATE TYPE,
# which would make the type's lifecycle invisible in this file.
date_override_type = postgresql.ENUM(
    "blocked",
    "custom_hours",
    name="date_override_type",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # HAND-WRITTEN: create the enum type explicitly before any table uses it.
    date_override_type.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "availability_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "day_of_week BETWEEN 0 AND 6", name=op.f("ck_availability_rules_day_of_week_range")
        ),
        sa.CheckConstraint(
            "end_time > start_time", name=op.f("ck_availability_rules_end_after_start")
        ),
        sa.CheckConstraint(
            "end_time < TIME '24:00:00'", name=op.f("ck_availability_rules_end_time_before_24h")
        ),
        sa.CheckConstraint(
            "start_time < TIME '24:00:00'", name=op.f("ck_availability_rules_start_time_before_24h")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_availability_rules")),
    )
    op.create_index(
        "ix_availability_rules_day_of_week", "availability_rules", ["day_of_week"], unique=False
    )
    op.create_table(
        "date_overrides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        # HAND-WRITTEN: was sa.Enum(...), which would emit a second CREATE TYPE.
        sa.Column("type", date_override_type, nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(type = 'blocked' AND start_time IS NULL AND end_time IS NULL) OR (type = 'custom_hours' AND start_time IS NOT NULL AND end_time IS NOT NULL AND end_time > start_time)",
            name=op.f("ck_date_overrides_hours_match_type"),
        ),
        sa.CheckConstraint(
            "end_time < TIME '24:00:00'", name=op.f("ck_date_overrides_end_time_before_24h")
        ),
        sa.CheckConstraint(
            "start_time < TIME '24:00:00'", name=op.f("ck_date_overrides_start_time_before_24h")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_date_overrides")),
    )
    op.create_index(op.f("ix_date_overrides_date"), "date_overrides", ["date"], unique=False)
    # Partial unique index: at most one blocked row per date, while any number
    # of custom_hours rows remain allowed for a split day.
    op.create_index(
        "uq_date_overrides_blocked_date",
        "date_overrides",
        ["date"],
        unique=True,
        postgresql_where=sa.text("type = 'blocked'"),
    )
    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("price_pkr", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("price_usd", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("buffer_before_minutes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("buffer_after_minutes", sa.Integer(), server_default="0", nullable=False),
        # HAND-WRITTEN: was app.db.types.IntakeQuestions(astext_type=Text()),
        # which references application code and an undefined name. The column is
        # JSONB; validation lives in the ORM type, not in the database.
        sa.Column(
            "intake_questions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(price_pkr IS NULL OR price_pkr >= 0) AND (price_usd IS NULL OR price_usd >= 0)",
            name=op.f("ck_services_prices_non_negative"),
        ),
        sa.CheckConstraint(
            "buffer_before_minutes >= 0 AND buffer_after_minutes >= 0",
            name=op.f("ck_services_buffers_non_negative"),
        ),
        sa.CheckConstraint("duration_minutes > 0", name=op.f("ck_services_duration_positive")),
        sa.CheckConstraint(
            "price_pkr IS NOT NULL OR price_usd IS NOT NULL",
            name=op.f("ck_services_at_least_one_price"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
    )
    op.create_index(op.f("ix_services_slug"), "services", ["slug"], unique=True)
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "host_timezone", sa.String(length=64), server_default="Asia/Karachi", nullable=False
        ),
        sa.Column("min_notice_hours", sa.Integer(), server_default="12", nullable=False),
        sa.Column("max_bookings_per_day", sa.Integer(), server_default="5", nullable=False),
        sa.Column("slot_granularity_minutes", sa.Integer(), server_default="15", nullable=False),
        sa.Column("cancellation_cutoff_hours", sa.Integer(), server_default="24", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cancellation_cutoff_hours >= 0",
            name=op.f("ck_settings_cancellation_cutoff_non_negative"),
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_settings_singleton")),
        sa.CheckConstraint(
            "max_bookings_per_day > 0", name=op.f("ck_settings_max_bookings_positive")
        ),
        sa.CheckConstraint(
            "min_notice_hours >= 0", name=op.f("ck_settings_min_notice_non_negative")
        ),
        sa.CheckConstraint(
            "slot_granularity_minutes > 0", name=op.f("ck_settings_slot_granularity_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    op.drop_index(op.f("ix_services_slug"), table_name="services")
    op.drop_table("services")
    op.drop_index("uq_date_overrides_blocked_date", table_name="date_overrides")
    op.drop_index(op.f("ix_date_overrides_date"), table_name="date_overrides")
    op.drop_table("date_overrides")
    op.drop_index("ix_availability_rules_day_of_week", table_name="availability_rules")
    op.drop_table("availability_rules")
    # ### end Alembic commands ###

    # HAND-WRITTEN: dropping the tables leaves the enum type in the database.
    # Without this, `downgrade` then `upgrade` fails with
    # "type date_override_type already exists".
    date_override_type.drop(op.get_bind(), checkfirst=True)
