"""booking models and availability minutes

Two things at once, because they land in the same branch:

  1. `availability_rules` and `date_overrides` move their wall-clock columns
     from TIME to INTEGER minutes-from-midnight, renamed `start_minute` /
     `end_minute`.
  2. `bookings`, `payments` and `intake_responses` are created, along with the
     exclusion constraint that prevents double-booking.

Revision 7c6380fb1b7c is NOT edited. It is merged and CI ran against it, so it
is immutable; the column change is expressed here as a forward migration.

Autogenerated, then hand-edited substantially. Every edit is marked
HAND-WRITTEN. The three that matter:

  * Autogenerate rendered the column change as add-column + drop-column, which
    silently **destroys every existing availability rule**. Replaced with
    ALTER COLUMN ... USING, which converts in place.
  * Dropping `start_time` / `end_time` would have taken
    `ck_date_overrides_hours_match_type` with it — Postgres drops CHECK
    constraints that depend on a dropped column — and autogenerate never
    emitted a replacement, because it compares check constraints by name only
    and the name did not change. The table would have silently lost the rule
    that keeps blocked and custom_hours rows coherent. Dropped and recreated
    explicitly.
  * `currency` is used by both `bookings` and `payments`, so autogenerate
    emitted CREATE TYPE for it twice. All five enum types are now created once,
    up front, with create_type=False on the columns.

Also hand-written: the exclusion constraint itself, which Alembic cannot
express, and the DROP TYPE calls in downgrade.

Note there is no `CREATE EXTENSION btree_gist`. It is not needed: btree_gist
exists to mix scalar equality into a GIST index (`host_id WITH =`), and this
constraint has no scalar column — it is single-tenant, and the status filter is
a WHERE predicate rather than a constraint column. `tstzrange` has GIST support
in core Postgres. Verified empirically against Postgres 16 before removing it.

Revision ID: c6bfff7c86ef
Revises: 7c6380fb1b7c
Create Date: 2026-08-11 03:38:20.634549

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c6bfff7c86ef"
down_revision: str | Sequence[str] | None = "7c6380fb1b7c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

MINUTES_PER_DAY = 1440

# HAND-WRITTEN: every enum type declared once, created explicitly, and applied
# to columns with create_type=False so create_table never emits its own
# CREATE TYPE. `currency` in particular is used by two tables.
booking_status = postgresql.ENUM(
    "pending_payment",
    "confirmed",
    "completed",
    "expired",
    "cancelled",
    "rescheduled",
    "no_show",
    name="booking_status",
    create_type=False,
)
currency = postgresql.ENUM("PKR", "USD", name="currency", create_type=False)
cancellation_reason = postgresql.ENUM(
    "invitee_requested",
    "host_cancelled",
    "payment_rejected",
    "payment_expired",
    "no_show_policy",
    name="cancellation_reason",
    create_type=False,
)
payment_provider = postgresql.ENUM(
    "manual_bank_transfer",
    "external_checkout",
    name="payment_provider",
    create_type=False,
)
payment_status = postgresql.ENUM(
    "pending", "succeeded", "failed", "refunded", name="payment_status", create_type=False
)

NEW_ENUMS = (booking_status, currency, cancellation_reason, payment_provider, payment_status)


def _time_to_minutes(column: str) -> str:
    """SQL converting a TIME column to minutes from midnight."""
    return f"(EXTRACT(HOUR FROM {column})::int * 60 + EXTRACT(MINUTE FROM {column})::int)"


def _minutes_to_time(column: str) -> str:
    """SQL converting minutes back to TIME, for the downgrade path.

    Minute 1440 is clamped to 23:59:59 rather than becoming '24:00:00'. The old
    schema's CHECK forbade 24:00:00 — for good reason, since Python cannot read
    it back — so a midnight-ending window cannot round-trip. The downgrade is
    therefore lossy by one second for such rows, which is preferable to a
    downgrade that simply fails.
    """
    return (
        f"(CASE WHEN {column} >= {MINUTES_PER_DAY} THEN TIME '23:59:59' "
        f"ELSE (TIME '00:00' + make_interval(mins => {column})) END)"
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ------------------------------------------------------------------
    # HAND-WRITTEN: availability_rules TIME -> INTEGER minutes, in place.
    # Constraints referencing the old columns must go first: a CHECK
    # comparing the column to TIME '24:00:00' cannot survive the retype.
    # ------------------------------------------------------------------
    op.drop_constraint(
        op.f("ck_availability_rules_start_time_before_24h"), "availability_rules", type_="check"
    )
    op.drop_constraint(
        op.f("ck_availability_rules_end_time_before_24h"), "availability_rules", type_="check"
    )
    op.drop_constraint(
        op.f("ck_availability_rules_end_after_start"), "availability_rules", type_="check"
    )

    op.execute(
        f"ALTER TABLE availability_rules "
        f"  ALTER COLUMN start_time TYPE integer USING {_time_to_minutes('start_time')}, "
        f"  ALTER COLUMN end_time   TYPE integer USING {_time_to_minutes('end_time')}"
    )
    op.alter_column("availability_rules", "start_time", new_column_name="start_minute")
    op.alter_column("availability_rules", "end_time", new_column_name="end_minute")

    op.create_check_constraint(
        op.f("ck_availability_rules_start_minute_range"),
        "availability_rules",
        f"start_minute >= 0 AND start_minute <= {MINUTES_PER_DAY}",
    )
    op.create_check_constraint(
        op.f("ck_availability_rules_end_minute_range"),
        "availability_rules",
        f"end_minute >= 0 AND end_minute <= {MINUTES_PER_DAY}",
    )
    op.create_check_constraint(
        op.f("ck_availability_rules_end_after_start"),
        "availability_rules",
        "end_minute > start_minute",
    )

    # ------------------------------------------------------------------
    # HAND-WRITTEN: same for date_overrides. hours_match_type is dropped and
    # recreated explicitly — dropping the columns would have removed it
    # silently, and autogenerate never noticed because the name is unchanged.
    # ------------------------------------------------------------------
    op.drop_constraint(
        op.f("ck_date_overrides_start_time_before_24h"), "date_overrides", type_="check"
    )
    op.drop_constraint(
        op.f("ck_date_overrides_end_time_before_24h"), "date_overrides", type_="check"
    )
    op.drop_constraint(op.f("ck_date_overrides_hours_match_type"), "date_overrides", type_="check")

    op.execute(
        f"ALTER TABLE date_overrides "
        f"  ALTER COLUMN start_time TYPE integer USING {_time_to_minutes('start_time')}, "
        f"  ALTER COLUMN end_time   TYPE integer USING {_time_to_minutes('end_time')}"
    )
    op.alter_column("date_overrides", "start_time", new_column_name="start_minute")
    op.alter_column("date_overrides", "end_time", new_column_name="end_minute")

    op.create_check_constraint(
        op.f("ck_date_overrides_start_minute_range"),
        "date_overrides",
        f"start_minute >= 0 AND start_minute <= {MINUTES_PER_DAY}",
    )
    op.create_check_constraint(
        op.f("ck_date_overrides_end_minute_range"),
        "date_overrides",
        f"end_minute >= 0 AND end_minute <= {MINUTES_PER_DAY}",
    )
    op.create_check_constraint(
        op.f("ck_date_overrides_hours_match_type"),
        "date_overrides",
        "(type = 'blocked' AND start_minute IS NULL AND end_minute IS NULL) "
        "OR (type = 'custom_hours' AND start_minute IS NOT NULL "
        "AND end_minute IS NOT NULL AND end_minute > start_minute)",
    )

    # ------------------------------------------------------------------
    # HAND-WRITTEN: create every enum type once, before any table uses one.
    # ------------------------------------------------------------------
    bind = op.get_bind()
    for enum_type in NEW_ENUMS:
        enum_type.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("status", booking_status, server_default="pending_payment", nullable=False),
        sa.Column("starts_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("blocked_range", postgresql.TSTZRANGE(), nullable=False),
        sa.Column("invitee_name", sa.String(length=200), nullable=False),
        sa.Column("invitee_email", sa.String(length=320), nullable=False),
        sa.Column("invitee_timezone", sa.String(length=64), nullable=False),
        sa.Column("invitee_phone", sa.String(length=32), nullable=True),
        sa.Column("currency", currency, nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("google_calendar_event_id", sa.String(length=1024), nullable=True),
        sa.Column("meet_link", sa.Text(), nullable=True),
        sa.Column("cancellation_token", sa.String(length=64), nullable=False),
        sa.Column("notes_private", sa.Text(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_reason", cancellation_reason, nullable=True),
        sa.Column("rescheduled_from_id", sa.Integer(), nullable=True),
        sa.Column("utm_source", sa.String(length=200), nullable=True),
        sa.Column("utm_medium", sa.String(length=200), nullable=True),
        sa.Column("utm_campaign", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(cancelled_at IS NULL) = (cancellation_reason IS NULL)",
            name=op.f("ck_bookings_cancellation_fields_together"),
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_bookings_amount_non_negative")),
        sa.CheckConstraint(
            "ends_at_utc > starts_at_utc", name=op.f("ck_bookings_ends_after_starts")
        ),
        sa.CheckConstraint(
            "rescheduled_from_id IS NULL OR rescheduled_from_id <> id",
            name=op.f("ck_bookings_not_rescheduled_from_self"),
        ),
        sa.ForeignKeyConstraint(
            ["rescheduled_from_id"],
            ["bookings.id"],
            name=op.f("fk_bookings_rescheduled_from_id_bookings"),
            # RESTRICT: a delete must fail rather than sever a reschedule chain.
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_bookings_service_id_services"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
    )
    op.create_index(
        op.f("ix_bookings_cancellation_token"), "bookings", ["cancellation_token"], unique=True
    )
    op.create_index(op.f("ix_bookings_invitee_email"), "bookings", ["invitee_email"], unique=False)
    op.create_index(
        op.f("ix_bookings_rescheduled_from_id"), "bookings", ["rescheduled_from_id"], unique=False
    )
    op.create_index(op.f("ix_bookings_service_id"), "bookings", ["service_id"], unique=False)
    op.create_index("ix_bookings_starts_at_utc", "bookings", ["starts_at_utc"], unique=False)
    op.create_index(op.f("ix_bookings_status"), "bookings", ["status"], unique=False)
    op.create_table(
        "intake_responses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("question_key", sa.String(length=50), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_intake_responses_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intake_responses")),
        sa.UniqueConstraint(
            "booking_id", "question_key", name="uq_intake_responses_booking_id_question_key"
        ),
    )
    op.create_index(
        op.f("ix_intake_responses_booking_id"), "intake_responses", ["booking_id"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("provider", payment_provider, nullable=False),
        sa.Column("provider_reference", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", currency, nullable=False),
        sa.Column("status", payment_status, server_default="pending", nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("receipt_url", sa.Text(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.String(length=320), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(verified_at IS NULL) = (verified_by IS NULL)",
            name=op.f("ck_payments_verification_fields_together"),
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_payments_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_payments_booking_id_bookings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index(op.f("ix_payments_booking_id"), "payments", ["booking_id"], unique=False)
    op.create_index(
        op.f("ix_payments_provider_reference"), "payments", ["provider_reference"], unique=False
    )
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # HAND-WRITTEN: the exclusion constraint. Alembic has no way to express
    # this, so it is raw SQL and always will be.
    #
    #   EXCLUDE USING gist (blocked_range WITH &&)
    #     -> no two rows may have overlapping blocked_range
    #   WHERE (status IN ('pending_payment','confirmed'))
    #     -> a partial index, so cancelled/expired/completed bookings do not
    #        hold their slot and it can be booked again
    #
    # blocked_range carries '[)' bounds, set by the application, so two
    # back-to-back bookings sharing an endpoint do NOT overlap. With the
    # default '[]' bounds they would, and the second booking would be
    # rejected for no reason.
    # ------------------------------------------------------------------
    op.execute(
        "ALTER TABLE bookings ADD CONSTRAINT excl_bookings_no_overlap "
        "EXCLUDE USING gist (blocked_range WITH &&) "
        "WHERE (status IN ('pending_payment', 'confirmed'))"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # HAND-WRITTEN: constraint goes with the table, but drop it explicitly so
    # the intent is visible rather than implied by DROP TABLE.
    op.execute("ALTER TABLE bookings DROP CONSTRAINT IF EXISTS excl_bookings_no_overlap")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_provider_reference"), table_name="payments")
    op.drop_index(op.f("ix_payments_booking_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_intake_responses_booking_id"), table_name="intake_responses")
    op.drop_table("intake_responses")
    op.drop_index(op.f("ix_bookings_status"), table_name="bookings")
    op.drop_index("ix_bookings_starts_at_utc", table_name="bookings")
    op.drop_index(op.f("ix_bookings_service_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_rescheduled_from_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_invitee_email"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_cancellation_token"), table_name="bookings")
    op.drop_table("bookings")
    # ### end Alembic commands ###

    # HAND-WRITTEN: dropping tables leaves the enum types behind, so a
    # downgrade-then-upgrade would fail with "type already exists".
    bind = op.get_bind()
    for enum_type in NEW_ENUMS:
        enum_type.drop(bind, checkfirst=True)

    # HAND-WRITTEN: minutes back to TIME. Lossy at exactly one value — see
    # _minutes_to_time().
    op.drop_constraint(op.f("ck_date_overrides_hours_match_type"), "date_overrides", type_="check")
    op.drop_constraint(op.f("ck_date_overrides_end_minute_range"), "date_overrides", type_="check")
    op.drop_constraint(
        op.f("ck_date_overrides_start_minute_range"), "date_overrides", type_="check"
    )
    op.execute(
        f"ALTER TABLE date_overrides "
        f"  ALTER COLUMN start_minute TYPE time USING {_minutes_to_time('start_minute')}, "
        f"  ALTER COLUMN end_minute   TYPE time USING {_minutes_to_time('end_minute')}"
    )
    op.alter_column("date_overrides", "start_minute", new_column_name="start_time")
    op.alter_column("date_overrides", "end_minute", new_column_name="end_time")
    op.create_check_constraint(
        op.f("ck_date_overrides_start_time_before_24h"),
        "date_overrides",
        "start_time < TIME '24:00:00'",
    )
    op.create_check_constraint(
        op.f("ck_date_overrides_end_time_before_24h"),
        "date_overrides",
        "end_time < TIME '24:00:00'",
    )
    op.create_check_constraint(
        op.f("ck_date_overrides_hours_match_type"),
        "date_overrides",
        "(type = 'blocked' AND start_time IS NULL AND end_time IS NULL) "
        "OR (type = 'custom_hours' AND start_time IS NOT NULL "
        "AND end_time IS NOT NULL AND end_time > start_time)",
    )

    op.drop_constraint(
        op.f("ck_availability_rules_end_after_start"), "availability_rules", type_="check"
    )
    op.drop_constraint(
        op.f("ck_availability_rules_end_minute_range"), "availability_rules", type_="check"
    )
    op.drop_constraint(
        op.f("ck_availability_rules_start_minute_range"), "availability_rules", type_="check"
    )
    op.execute(
        f"ALTER TABLE availability_rules "
        f"  ALTER COLUMN start_minute TYPE time USING {_minutes_to_time('start_minute')}, "
        f"  ALTER COLUMN end_minute   TYPE time USING {_minutes_to_time('end_minute')}"
    )
    op.alter_column("availability_rules", "start_minute", new_column_name="start_time")
    op.alter_column("availability_rules", "end_minute", new_column_name="end_time")
    op.create_check_constraint(
        op.f("ck_availability_rules_start_time_before_24h"),
        "availability_rules",
        "start_time < TIME '24:00:00'",
    )
    op.create_check_constraint(
        op.f("ck_availability_rules_end_time_before_24h"),
        "availability_rules",
        "end_time < TIME '24:00:00'",
    )
    op.create_check_constraint(
        op.f("ck_availability_rules_end_after_start"),
        "availability_rules",
        "end_time > start_time",
    )
