"""supporting tables: admin users, webhook events, notification log

Autogenerated, then hand-edited in three marked places:

  1. `totp_secret` rendered as `app.db.types.EncryptedString()`, referencing
     application code that this file must outlive — and `app` is not even
     imported, so the migration would fail on import. Replaced with `sa.Text()`.
     The encryption lives in the ORM type; the column really is TEXT, and the
     database neither knows nor cares that the bytes are ciphertext.
  2. The three notification enums were created implicitly by `create_table`,
     which works on the way up but leaves the types behind on the way down —
     so downgrade-then-upgrade fails with "type already exists". Declared
     explicitly and created once, with `create_type=False` on the columns.
  3. `downgrade()` drops the three enum types.

Note `raw_body` is BYTEA (`sa.LargeBinary`), not TEXT or JSONB. Webhook
signature verification is an HMAC over the exact bytes on the wire, and any
re-serialisation — JSON key order, whitespace, unicode escaping, a trailing
newline — changes them. A parsed-and-redumped copy would produce a different
signature from the one the provider sent, which makes it actively misleading
when a signature mismatch is the bug being chased.

Revision ID: bc737c0339e0
Revises: c6bfff7c86ef
Create Date: 2026-08-11 04:49:06.241783

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "bc737c0339e0"
down_revision: str | Sequence[str] | None = "c6bfff7c86ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# HAND-WRITTEN: declared once so upgrade and downgrade agree, and so the
# types' lifecycle is visible in this file rather than implied by create_table.
notification_type = postgresql.ENUM(
    "booking_confirmed",
    "reminder_24h",
    "reminder_1h",
    "cancelled",
    "rescheduled",
    "manual_payment_received",
    "manual_payment_rejected",
    name="notification_type",
    create_type=False,
)
notification_channel = postgresql.ENUM("email", name="notification_channel", create_type=False)
notification_status = postgresql.ENUM(
    "queued", "sent", "failed", name="notification_status", create_type=False
)

NEW_ENUMS = (notification_type, notification_channel, notification_status)


def upgrade() -> None:
    """Upgrade schema."""
    # HAND-WRITTEN: create the enum types once, before any table uses one.
    bind = op.get_bind()
    for enum_type in NEW_ENUMS:
        enum_type.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        # HAND-WRITTEN: was app.db.types.EncryptedString(), an application import.
        sa.Column("totp_secret", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_users")),
    )
    op.create_index(op.f("ix_admin_users_email"), "admin_users", ["email"], unique=True)
    op.create_table(
        "processed_webhook_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_event_id", sa.String(length=255), nullable=False),
        sa.Column("raw_body", sa.LargeBinary(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processed_webhook_events")),
        sa.UniqueConstraint(
            "provider",
            "provider_event_id",
            name="uq_processed_webhook_events_provider_provider_event_id",
        ),
    )
    op.create_index(
        "ix_processed_webhook_events_event_type",
        "processed_webhook_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_processed_webhook_events_received_at"),
        "processed_webhook_events",
        ["received_at"],
        unique=False,
    )
    op.create_table(
        "notification_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("type", notification_type, nullable=False),
        sa.Column("channel", notification_channel, server_default="email", nullable=False),
        sa.Column("status", notification_status, server_default="queued", nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'sent') = (sent_at IS NOT NULL)",
            name=op.f("ck_notification_log_sent_at_matches_status"),
        ),
        sa.CheckConstraint(
            "retry_count = 0 OR last_attempted_at IS NOT NULL",
            name=op.f("ck_notification_log_retried_rows_have_an_attempt_time"),
        ),
        sa.CheckConstraint(
            "retry_count >= 0", name=op.f("ck_notification_log_retry_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_notification_log_booking_id_bookings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_log")),
    )
    op.create_index(
        op.f("ix_notification_log_booking_id"), "notification_log", ["booking_id"], unique=False
    )
    op.create_index(
        op.f("ix_notification_log_status"), "notification_log", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_log_status"), table_name="notification_log")
    op.drop_index(op.f("ix_notification_log_booking_id"), table_name="notification_log")
    op.drop_table("notification_log")
    op.drop_index(
        op.f("ix_processed_webhook_events_received_at"), table_name="processed_webhook_events"
    )
    op.drop_index("ix_processed_webhook_events_event_type", table_name="processed_webhook_events")
    op.drop_table("processed_webhook_events")
    op.drop_index(op.f("ix_admin_users_email"), table_name="admin_users")
    op.drop_table("admin_users")
    # ### end Alembic commands ###

    # HAND-WRITTEN: dropping the tables leaves the enum types behind, so a
    # downgrade-then-upgrade would fail with "type already exists".
    bind = op.get_bind()
    for enum_type in NEW_ENUMS:
        enum_type.drop(bind, checkfirst=True)
